[package]
name = "PaperTrader"
version = "0.1.0"
authors = ["realaltffour <56314286+realaltffour@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "libtrader"
path = "src/libtrader/libtrader.rs"
test = true
bench = true

[[bin]]
name = "sandbox"
path = "src/bin/sandbox/sandbox.rs"
test = false
bench = false

[features]
default = ["master_server"]
master_server = []
worker_server = []
client = []

[dependencies]
chrono = "0.4"
postgres = "0.17.3"
postgres-types = {version = "0.1.1", features = ["derive"]}
log = "0.4"
simplelog = "0.8.0"
enum_primitive = "*"
os_type="2.2"
