use serde::{Serialize, Deserialize};

bitflags! {
    // TODO: FIX NUMBERING
    #[derive(Serialize, Deserialize)]
    pub struct ReturnFlags: u64 {
        const LIBTRADER_INIT_CLIENT_CONNECT = 0x001;
        const LIBTRADER_INIT_LOG_FAILED = 0x002;
        const LIBTRADER_INIT_FAILED = 0x003;
        const COMMON_GEN_LOG_DIR_CREATION_FAILED = 0x004;
        const COMMON_TLS_BAD_CONFIG = 0x005;

        const COMMON_GET_COMPANY_FAILED = 0x006;
        const COMMON_GET_STOCK_FAILED = 0x007;

        const SERVER_DB_CONNECT_FAILED = 0x008;
        const SERVER_DB_WRITE_FAILED = 0x008;

        const SERVER_REGISTER_INV_MSG = 0x008;
        const SERVER_LOGIN_INV_MSG = 0x009;

        const SERVER_PURCHASE_ASSET_INV_MSG = 0x00A;

        const SERVER_ACC_UNAUTHORIZED = 0x00B;
        const SERVER_ACC_USER_EXISTS = 0x00C;

        const SERVER_GET_ASSET_DATA_INV_MSG = 0x00D;
        const SERVER_GET_ASSET_INFO_INV_MSG = 0x00E;

        const SERVER_GET_USER_ID_NOT_FOUND = 0x00F;

        const SERVER_RETRIEVE_TRANSACTION_FAILED = 0x010;
        const SERVER_RETRIEVE_TRANSACTION_INV_MSG = 0x011;
        const SERVER_RETRIEVE_PORTFOLIO_FAILED = 0x012;
        const SERVER_RETRIEVE_PORTFOLIO_INV_MSG = 0x013;


        const SERVER_CREATE_COMPANY_FAILED = 0x014;
        const SERVER_CREATE_STOCK_FAILED = 0x015;

        const SERVER_CREATE_JWT_TOKEN_FAILED = 0x016;

        const SERVER_TLS_CONN_WRITE_FAILED = 0x017;
        const SERVER_TLS_CONN_PROCESS_FAILED = 0x018;
        const SERVER_TLS_CONN_READ_PLAIN_FAILED = 0x019;
        const SERVER_TLS_SERVER_ACCEPT_FAILED = 0x01A;

        const SERVER_HANDLE_DATA_RCVD_INV_MSG = 0x01B;

        const CLIENT_ACC_RETRIEVE_PORTFOLIO_ERROR = 0x01C;
        const CLIENT_ACC_RETRIEVE_TRANSACTION_ERROR = 0x01D;
        const CLIENT_ACC_CREATION_FAILED = 0x01E;

        const CLIENT_REQ_SALT_FAILED = 0x01F;
        const CLIENT_GEN_SALT_FAILED = 0x020;
        const CLIENT_TLS_READ_ERROR = 0x021;
    }
}
