name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Check Code Format
      run: cargo fmt --all -- --check
    - name: Build Minimal
      run: cargo build  --no-default-features
    - name: Build Client with TLS verification
      run: cargo build --no-default-features --features "client"
    - name: Build Client without TLS verification
      run: cargo build --no-default-features --features "client,tls_no_verify"
    - name: Build Server
      run: cargo build --no-default-features --features "server"
    - name: Build Hybrid
      run: cargo build --no-default-features --features "server,client"
